### ISSUE TITLE
Issues on Chrome mobile (Android 5.1.1)

### ISSUE THREAD

**Issue by IBwWG** [benawad/react-menu-monkey-client#3]
- [ ] can't see any recipes on the main recipe list (not logged in) (yes I've added some on desktop first :) )
- [ ] attempting to sign up just clears the form but never forwards to login page; a login is not created (as verified via desktop)
- [ ] attempting to log in (with login created via desktop) just clears the form

**Comment by IBwWG** [comment]
Chrome v 55.0.2883.91 (Official Build) (32-bit)

**Comment by benawad** [comment]
You would need to deploy the server to be able to use the website on your phone. The localhost server you are running on your computer cannot be seen by your phone, so when you open the website on your phone it tries to make a request to the server but it is not there and that's why you are these getting problems.

**Comment by IBwWG** [comment]
You mean 'localhost' is hard-coded in somewhere, even if I access it via its local IP?

**Comment by IBwWG** [comment]
Oh I see it in the config now.  My bad!  Thanks :)

**Comment by IBwWG** [comment]
Yep, that solves those three issues.  The only thing is the cards are a bit skinny when in profile orientation (even 8-char text overflows about double the width of each card), but otherwise everything seems to work great!

For anyone else finding this just modify the host in the client's `src/store.js` and in the backend's `config/default.json'.
